version: '3.4'

services:
  micro-mongo-discountdb:
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Admin1234@
    ports:
      - "27017:27017" 

  micro-sqlserver-catalogdb:
    restart: always
    environment:
      - MSSQL_SA_PASSWORD=Admin1234@
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  micro-discount-api:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb=mongodb://admin:Admin1234%40@micro-mongo-discountdb:27017/
    ports:
      - "8001:80"
    depends_on:
      - micro-mongo-discountdb

  micro-catalog-api:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=micro-sqlserver-catalogdb,1433;Database=Catalogdb;User ID=SA;Password=Admin1234@
      - ServiceApiUrls__DiscountApi=http://micro-discount-api:80
    ports:
      - "8002:80"
    depends_on:
      - micro-sqlserver-catalogdb

