# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  micro-rabbitmq-management:
    image: rabbitmq:management
    container_name: micro-rabbitmq-management

  micro-mongodb:
    image: mongo
    container_name: micro-mongodb

  micro-sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: micro-sqlserver

  micro-postgres:
    image: postgres
    container_name: micro-postgres

  micro-discount-api:
    image: micro-discount-api
    container_name: micro-discount-api
    build: 
      context: .
      dockerfile: Services\Discount\Discount.API\Dockerfile

  micro-catalog-api:
    image: micro-catalog-api
    container_name: micro-catalog-api
    build: 
      context: .
      dockerfile: Services\Catalog\Catalog.API\Dockerfile

  micro-identity-api:
    image: micro-identity-api
    container_name: micro-identity-api
    build: 
      context: .
      dockerfile: Services\Identity\Identity.API\Dockerfile

  micro-email-api:
    image: micro-email-api
    container_name: micro-email-api
    build: 
      context: .
      dockerfile: Services\Email\Email.API\Dockerfile

  micro-cart-api:
    image: micro-cart-api
    container_name: micro-cart-api
    build: 
      context: .
      dockerfile: Services\Cart\Cart.API\Dockerfile

  micro-order-api:
    image: micro-order-api
    container_name: micro-order-api
    build: 
      context: .
      dockerfile: Services\Order\Order.API\Dockerfile

  micro-apigateway-ocelot:
    image: micro-apigateway-ocelot
    container_name: micro-apigateway-ocelot
    build:
      context: .
      dockerfile: ApiGateways\OcelotApiGateway\Dockerfile
