# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  micro-mongo-discountdb:
    image: mongo
    container_name: micro-mongo-discountdb

  micro-sqlserver-catalogdb:
    image: mcr.microsoft.com/mssql/server
    container_name: micro-sqlserver-catalogdb

  micro-discount-api:
    image: micro-discount-api
    container_name: micro-discount-api
    build: 
      context: .
      dockerfile: Services\Discount\Discount.API\Dockerfile

  micro-catalog-api:
    image: micro-catalog-api
    container_name: micro-catalog-api
    build: 
      context: .
      dockerfile: Services\Catalog\Catalog.API\Dockerfile

