version: '3.4'

services:
  micro-mongo-discountdb:
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Admin1234@
    ports:
      - "27017:27017" 

  micro-discount-api:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb=mongodb://admin:Admin1234%40@micro-mongo-discountdb:27017/
    ports:
      - "8001:80"
    depends_on:
      - micro-mongo-discountdb